name: Build doxygen
on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: ["dev"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Check refs
      - run: |
          echo ${{ github.ref_name }}
          echo ${{ github.ref }}
          echo ${{ github.head_ref }}
